include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    avoid_positional_boolean_parameters: ignore
    comment_references: ignore
    lines_longer_than_80_chars: ignore
    prefer_constructors_over_static_methods: ignore
    invalid_annotation_target: ignore
    no_default_cases: ignore
    prefer_int_literals: ignore
    document_ignores: ignore
    avoid_catches_without_on_clauses: ignore
    one_member_abstracts: ignore

linter:
  rules:
    discarded_futures: false

formatter:
  page_width: 120
  trailing_commas: preserve
